# wrangler.toml
name = "character-db"
main = "./.output/server/index.mjs"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./.output/public"

[assets]
binding = "PUBLIC"
directory = "./.output/public"
